### ISSUE TITLE
Verify PEC Error: ONLY from build version appear this error

### ISSUE THREAD

**Issue by zitelog** [fit-project/fit#106]
![image](https://github.com/fit-project/fit/assets/1495067/bce61607-cbe1-41e6-b6d1-4fea3f5f3d16)

**Comment by fpollicelli** [comment]
Could the problem be this?
![image](https://github.com/fit-project/fit/assets/45490701/6af830c7-22b0-4208-a427-3cadb8d45ef9)

**Comment by zitelog** [comment]
I'm getting old, I forgot to copy this 

![image](https://github.com/fit-project/fit/assets/1495067/4561fe5f-e01a-4f77-b947-9d43839ae12b)
