### ISSUE TITLE
Problems with Instagram acquisition

### ISSUE THREAD

**Issue by franccost2001** [fit-project/fit#107]
Hi guys. I wanted to report the following login problem:

JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

**Comment by dpalmisano26** [comment]
Hi, it's a problem related to the library used for that tool. We are working on it. 

Thanks for the report.
