### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by cfda-nu** [fit-project/fit#118]
salve, ricevo un errore di login in fase di acquisizione di un profilo Instagram. grazie 

![Connection_error](https://github.com/fit-project/fit/assets/157822375/4d082890-090e-4967-89af-3f24e8323d7e)

**Comment by zitelog** [comment]
Salve il baco è risolto nella versione 1.3 non c'è ancora le versione exe. A breve dovremmo rilasciarla

**Comment by cfda-nu** [comment]
Ringrazio mille,
spero che avvenga il prima possibile il rilascio....ho una delega da
evadere particolarmente delicata.
Complimenti per il progetto, ottimo direi.
Lillo


Il ven 26 gen 2024, 21:15 Fabio Zito ***@***.***> ha scritto:
