### ISSUE TITLE
New scraper for acquisition entire site

### ISSUE THREAD

**Issue by zitelog** [fit-project/fit#45]
Proposal to improve from [@mattiaepi](https://github.com/mattiaepi) it would be nice to make a scrapper that starting from an URL crawls and downloads the entire site like [httrack ](http://www.httrack.com/ )and in the meantime records info like network traffic, hash calculation, report creation, etc.

**Comment by fpollicelli** [comment]
Should the scraper be an automated tool (similar to httrack), or should it look like our web acquisition tool, with an interface for navigating through the pages of the website before downloading it?

**Comment by Lazza** [comment]
IMHO this requires (and will be much facilitated by) either the mitmproxy integration or a WARC generation (done live during the acquisition).

**Comment by zitelog** [comment]
> Should the scraper be an automated tool (similar to httrack), or should it look like our web acquisition tool, with an interface for navigating through the pages of the website before downloading it?

I think the best way is try to httrack!

But, in my mind, the user experience should be similar to our video scrapper, as illustrated below:

1) Insert the domain url (eg. https://www.realitynet.it/) 
2) Click "Load site" button
3) Search if  sitemap exists
4) If sitemap doesn't exist crawal the site to create it
5) Show the sitemap URLs, eg as the following:
     - https://www.realitynet.it/ (home)
     - https://www.realitynet.it/services/ (servizi)
     - https://www.realitynet.it/the-mission/ (mission)
     - ...
6) It's possibile to select each one (default all url are selected) as in our mail scrapper
7) It's possibile to add custom URL in the list shown in point 4
8) Click "Download" button
9) First download all selected URL and then create the "forensic" artifacates

**Comment by fpollicelli** [comment]
How do we manage websites that require access through credentials?

**Comment by zitelog** [comment]
> How do we manage websites that require access through credentials?

We start with public sites, then will see...

**Comment by Lazza** [comment]
> How do we manage websites that require access through credentials?

The session should start interactively so that FIT can store cookies.

My main concern is about websites that heavily rely on JS, e.g. all major social networks.
