### ISSUE TITLE
Report in PDF

### ISSUE THREAD

**Issue by zitelog** [fit-project/fit#52]
Proposta di miglioramento fatta da[@ImSasuk3](https://github.com/ImSasuk3)

- Aggiungere la possibilità di selezionare un logo immagine e/o testuale per il report.
- Aggiungere nel report gli screenshot eseguiti con i relativi hyperlink al file originale ed anche alla video registrazioni 
- Aggiungerei qualche informazione in più su FIT inserendo il link dove reperirlo.

**Comment by fpollicelli** [comment]
Non ho capito cosa intendi per "selezionare un logo immagine e/o testuale per il report", potresti chiarire?
