### ISSUE TITLE
Nuovo scrapper per acquisizione audio 

### ISSUE THREAD

**Issue by zitelog** [fit-project/fit#53]
Proposta di miglioramento fatta da[@ImSasuk3](https://github.com/ImSasuk3)

- registrazione audio fonte (ex video YouTube)

**Comment by fpollicelli** [comment]
Il tool video permette di estrarre l'audio della fonte, è questa la richiesta?

**Comment by zitelog** [comment]
> Il tool video permette di estrarre l'audio della fonte, è questa la richiesta?

Direi di si!
