### ISSUE TITLE
Non  è chiaro cosa è necessario fare in caso di 2FA sia per la PEC che per scaricare mail

### ISSUE THREAD

**Issue by zitelog** [fit-project/fit#55]
Proposta di miglioramento fatta da[@ImSasuk3](https://github.com/ImSasuk3)

**Comment by fpollicelli** [comment]
Si potrebbe pensare di aggiungere un link che riporti a delle istruzioni? Un po' come avviene per la lista di siti supportati dal tool Video
![image](https://github.com/fit-project/fit/assets/45490701/e2b11c5e-5ce2-44d6-a8bd-2d336441fc57)

**Comment by zitelog** [comment]
> Si potrebbe pensare di aggiungere un link che riporti a delle istruzioni? Un po' come avviene per la lista di siti supportati dal tool Video ![image](https://user-images.githubusercontent.com/45490701/251707016-e2b11c5e-5ce2-44d6-a8bd-2d336441fc57.png)

Ok qualcosa del genere! non so però se esiste già una pagina che in modo generico spiega cosa fare per ogni provider di posta! forse dovremmo aggiungerlo al nostro wiki e poi consigliare di andare sulla pagina del proprio provider per capire cosa fare.

![image](https://github.com/fit-project/fit/assets/1495067/91682b7a-b3d3-4f9e-9d6c-c19f97a4b9a1)

**Comment by Lazza** [comment]
The target user base for FIT (DFIR **professionals**) should be well aware of what an "app specific password" is, though.
