### ISSUE TITLE
From the onefile build of pyinstaller get the assets folder and the whois folder directly from "unzipped" directory

### ISSUE THREAD

**Issue by zitelog** [fit-project/fit#99]
After that, remove this step from the wiki
![image](https://github.com/fit-project/fit/assets/1495067/579d803f-9a11-4eed-9fbb-505bd5862e75)

**Comment by Lazza** [comment]
Ah, nice one. I wanted to open an issue about this one and then I forgot.

Not sure what you mean by "from the _MEIXXXXXX folder", though.

**Comment by zitelog** [comment]
> Ah, nice one. I wanted to open an issue about this one and then I forgot.
> 
> Not sure what you mean by "from the _MEIXXXXXX folder", though.

This directory is created automatically in the temp-dir  when FIT.exe is "unzipped", e.g. \Temp\_MEI198722. The "_MEI" part is a static suffix, while the numeric part is random. This directory is automatically deleted if FIT is closed without crashing.

**Comment by Lazza** [comment]
I don't think you should be concerned with said directory. The Pyinstaller file already contains provisions to copy the `assets` folder. What is missing is the `whois` part.

https://github.com/fit-project/fit/blob/2cf241469c86b1f7ffa115e91ce7002dc60c244c/pyinstaller/windows/fit-console.spec#L11

**Comment by zitelog** [comment]
> I don't think you should be concerned with said directory. The Pyinstaller file already contains provisions to copy the `whois` folder. What is missing is the `assets` part.
> 
> https://github.com/fit-project/fit/blob/2cf241469c86b1f7ffa115e91ce7002dc60c244c/pyinstaller/windows/fit-console.spec#L11

I tried to correct the title maybe so it's less ambiguous!
